Added reverse-proxy service.
mdenet/educationplatform-docker pull request #67
Opened 2024-12-12 17:59 UTC by aryaei2000

#66 fix for incorporating a reverse proxy server into the docker compose environment using the latest version of Nginx. 

A few things to do to make it better:

- Put all ports in the environment file so that configuration can be done more easily
- Run the discovery service from here and keep the port to path mapping in one container only

2024-12-13 09:51 UTC, szschaler commented
Building fails. It seems the key message is this:

``
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/runner/work/educationplatform-docker/educationplatform-docker/reverse-proxy/default.conf" to rootfs at "/etc/nginx/conf.d/default.conf": create mountpoint for /etc/nginx/conf.d/default.conf mount: cannot create subdirectories in "/var/lib/docker/overlay2/b449b4363e6c7e5dbae0d258baa6d5149cff1619044538a5c5cba8f749eb0f1c/merged/etc/nginx/conf.d/default.conf": not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
``

Does the required config file exist on the repository and therefore on the GitHub Action build server?

2024-12-13 10:00 UTC, szschaler requested changes
Some comments and requests for change...

2024-12-13 10:00 UTC, szschaler commented on config/reverse-proxy.conf
> +    #error_page  404              /404.html;
Which service does that file live on? Should it go to the EP service?

2025-01-06 16:57 UTC, aryaei2000 commented on config/reverse-proxy.conf
> +        location /tools/conversion/ {
Must be VS code doing something unusual. Indentation is just for readability.

2025-01-06 16:59 UTC, aryaei2000 commented on config/reverse-proxy.conf
> +    #error_page  404              /404.html;
We currently don't have a custom 404 or 500. The default pages on our load balancer are shown. This specific line is commented and not effective.

2025-01-06 17:37 UTC, aryaei2000 commented on docker-compose.yml
> +            - "8081:80"
The load balancer can be configured via our portal. As well, the gateway port must be open in OpenStack.

2025-01-14 02:55 UTC, aryaei2000 commented on docker-compose.yml
> +            - "8081:80"
Reverse proxy port is now set to 8080 and education platform is set to 8081.

2025-01-14 09:20 UTC, szschaler requested changes
Just one update to README, then looks ready to go...

I assume you have tested this on the dev server and it works there?

2025-01-14 09:20 UTC, szschaler commented on README.md
> +The containerised version of the platform can be deployed on a web server behind a load balancer using reverse proxy. For instance, an Nginx server can be configured to directly run on the host machi
This should be updated to reflect the fact that that reverse proxy is now included in the docker-compose file already.

2025-01-14 13:08 UTC, aryaei2000 commented on README.md
> +The containerised version of the platform can be deployed on a web server behind a load balancer using reverse proxy. For instance, an Nginx server can be configured to directly run on the host machi
Documentation updated:

https://raw.githubusercontent.com/mdenet/educationplatform-examples/main/epsilon-example/epsilon-example_activity.yml

2025-01-14 13:13 UTC, szschaler approved these changes

2025-01-14 13:16 UTC, szschaler commented
Looks to be working on dev server now...

2025-01-14 15:10 UTC, szschaler commented on README.md
> +The containerised version of the platform can be deployed on a web server behind a load balancer using reverse proxy. For instance, an Nginx server can be configured to directly run on the host machi
I don't understand this link here?

2025-01-15 10:48 UTC, aryaei2000 commented on README.md
> +The containerised version of the platform can be deployed on a web server behind a load balancer using reverse proxy. For instance, an Nginx server can be configured to directly run on the host machi
Sorry wrong link! Was meant to be:

https://github.com/mdenet/educationplatform/blob/d28a246c47fc4174e53fdf1355fe294a01060b64/README.md?plain=1#L37

2025-01-15 10:49 UTC, aryaei2000 commented
Submodules updated.

2025-01-15 12:34 UTC, szschaler approved these changes

2025-01-15 12:52 UTC, merged